# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1649f30c0ad08109bcd2c531ed58be0d5806aac35c763284142a7d1d1d35bbecaa9b43cead50114964149b43d1d56a580da28cc7494d1ab36bea1858a2d4de71

test:
  secret_key_base: 056b72d708b06b2742e4818b52a53325a64726c4c1bc86b6f219a3834d8a81c18b4d830992f04a889e0a4f2b2b44add7852a1675d5a9f5ae53fb5f21928ae93f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
